version: '3.8'

services:
  nginx:
    image: vgerton/my-nginx:latest
    ports:
      - "8888:80"
    deploy:
      replicas: 1

  db:
    image: vgerton/db:latest
    ports:
      - "5432:5432"
    env_file:
      - db.env
    networks:
      - my-network

  app:    
    image: vgerton/docker-task:latest
    ports:
      - "8080:8080"
    env_file:
      - app.env
    depends_on:
      db:
        condition: service_started
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
