version: '3.8'

services:
  db:
    image: vgerton/db:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password

  app:    
    image: vgerton/docker-task:latest
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_started