services:

  nginx:
    image: vgerton/my-nginx:latest
    ports:
      - "80"
    deploy:
      mode: replicated
      replicas: 5

  db:
    image: vgerton/db:latest
    ports:
      - "5432:5432"
    env_file:
      - db.env

  app:
    image: vgerton/docker-task:latest
    ports:
      - "8080:8080"
    env_file:
      - app.env
    depends_on:
      db:
        condition: service_started
