spring:
  datasource:
    url: jdbc:postgresql://db:5432/user_db
    username: test_user
    password: test_password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  threads:
    virtual:
      enabled: true
