apiVersion: v1
kind: ConfigMap
metadata:
  name: app-env-2
data:
  {{- range $key, $value := .Values.app.env }}
    {{ $key }}: {{ $value }}
    {{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-env-2
data:
  {{- range $key, $value := .Values.db.env }}
    {{ $key }}: {{ $value }}
    {{- end }}