apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
spec:
  selector:
    app: {{ .Values.app.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.app.port }}
      targetPort: {{ .Values.app.port }}
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.name }}
spec:
  selector:
    app: {{ .Values.db.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.db.port }}
      targetPort: {{ .Values.db.port }}
  type: ClusterIP